name: face-recognition-api-go

networks:
  face-infra:
    external: true

services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    networks:
      - face-infra
    restart: unless-stopped
